= Analytics
:description: Parallel data management for complex queries over many records, using a familiar {sqlpp} syntax.
:page-edition: Enterprise Edition:
:page-aliases: concept-docs:analytics-for-sdk-users.adoc
:lang: C++
:example-source: devguide:example$cxx/src/analytics.cxx
:example-source-lang: c++


[abstract]
{description}


For complex and long-running queries, involving large ad hoc join, set, aggregation, and grouping operations, Couchbase Data Platform offers the xref:{version-server}@server:analytics:introduction.adoc[Couchbase Analytics Service (CBAS)].
This is the analytic counterpart to our xref:sqlpp-queries-with-sdk.adoc[operational data focussed Query Service].

The analytics service is available in xref:cloud:clusters:analytics-service/analytics-service.adoc[Capella]
or the Enterprise Edition of xref:server:analytics:introduction.adoc[self-managed Couchbase Server].
A separate, as-a-service offering of Real-Time Analytics -- Capella Columnar -- is available as a https://info.couchbase.com/CapellaColumnar_Private_Preview_SignUp_LP.html[private preview].


== Getting Started

After familiarizing yourself with our xref:{version-server}@server:analytics:primer-beer.adoc[introductory primer],
in particular creating a dataset and linking it to a bucket to shadow the operational data,
try Couchbase Analytics using the {cpp} SDK.
Intentionally, the API for analytics is very similar to that of the query service.

Before starting, here's all imports used in the following examples:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=imports]
----

Here's a complete example of doing an analytics query and handling the results:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=analytics_query]
----

Let's break this down.
First, we get the results in the form of a `std::pair<couchbase::error, couchbase::analytics_result>`.

An `analytics_result` contains various things of interest, such as metrics, but the main thing we're interested in are the rows (results).
They're fetched with a  `rows_as_json` call.

We check explicitly for an `error` which indicates something went wrong during the analytics query call.
Please see xref:howtos:error-handling.adoc[Error Handling] for details.

Here we're fetching rows converted into JSON, but as with {sqlpp} (formerly N1QL) there's many more options available.
Rows can be returned as JSON representations from multiple third party {cpp} libraries, directly as a user defined class, and more.
Please see xref:howtos:json.adoc[JSON Libraries] for full details.

Finally, we iterate through the `rows`.

== Queries

A query can either be `simple` or be `parameterized`. If parameters are used, they can either be `positional` or `named`.
Here is one example of each:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=simple_parameters]
----

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=named_parameters]
----

== Additional Parameters

The handful of additional parameters are illustrated here:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=additional_parameters]
----

=== Metadata
`analytics_result::meta_data()` contains useful metadata, such as `elapsedTime`, and `resultCount`:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=metadata]
----

// For a full listing of available `Metrics` in `Metadata`, see the xref:concept-docs:analytics-for-sdk-users.adoc[Understanding Analytics] documentation.

////
== Additional Resources

To learn more about using {sqlpp} for Analytics -- the first commercial implementation of {sqlpp} -- see our https://sqlplusplus-tutorial.couchbase.com/tutorial/#1[Tutorial Introduction to SQL++ for SQL users].

////
