= Logging
:description:
:lang: C++
:example-source: devguide:example$cxx/src/logging.cxx
:example-source-lang: c++


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}

The Couchbase {cpp} SDK allows logging to be configured programmatically. Internally, the SDK uses the
https://github.com/gabime/spdlog[spdlog] logging library.

Once the logger has been initialized, The default log level is `info`.

The following log levels are supported (in order of increasing amount of information logged):

. off
. critical
. error
. warning
. info
. debug
. trace

The {cpp} SDK can be configured to send logs to standard output, or to a file.
The logger can be initialized and logging level changed like so:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=logging]
----


// ?? or can it ??






== SDK Telemetry from the Server

In addition to Tracing and other metrics, and client logging, SDK is telemetry is also sent to the Server -- available from 8.0, and in new Capella Operational clusters -- for ingestion with other Prometheus metrics.
Capella Operatioal exposes these metrics through the UI.

For self-managed Server, collection can be disabled and enabled through the REST API:

[source,console]
----
curl --user Administrator:password http://172.17.0.2:8091/settings/appTelemetry -d enabled=true
----

And the Prometheus-format metrics fetched with:

[source,console]
----
curl --user Administrator:password http://172.17.0.2:8091/metrics
----

There may be advantages to collecting information this way,
but note that metrics are collected per node,
and a central Prometheus instance should be set to collect all metrics so that information is not lost in case of a sudden failover.

Also note that if the cluster is behind a load balancer, the collected metrics may not accurately record the actual correct node with which the SDK interacts.

