= Async APIs
:description: The Couchbase {cpp} SDK allows the use, and mixing, of two asynchronous APIs.
// :description: The Couchbase Scala SDK allows the use, and mixing, of three distinct APIs: blocking, asynchronous, and reactive.
:page-toclevels: 2
// :page-aliases: ROOT:async-programming,multiple-apis,ROOT:batching-operations
:lang: C++
:example-source: devguide:example$cxx/src/async_apis.cxx
:example-source-lang: c++



// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at https://docs.couchbase.com/cxx-sdk/1.3/howtos/concurrent-async-apis.html

[abstract]
{description}

The {cpp} SDK provides two asynchronous APIs, which can be freely mixed:

* A future-based one, that returns a `std::future`
* A callback-based one, that takes a `std::function`

== Using the future-based API

The future-based API returns a {cpp} `std::future<T>`, representing the execution of an asynchronous task and the promise of a future result.

Here's what a simple upsert looks like, fetching the result with `std::future<T>::get()`:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=upsert_future]
----

== Using the callback-based API

The callback-based API takes a `std::function<T>`, containing the result of the operation once it becomes available.

Here is what a simple upsert looks like, using the callback-based API:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=upsert_callback]
----


== Choosing an API

So which API should you choose?

It's really down to you and the needs of your application.
If you're already writing code using callbacks then it may make sense to continue that way.
The callback-based API provides an easy and intuitive way to chain operations together, whereas the future-based API
provides a clean and modern way to access results of asynchronous operations.
And you can use different APIs at different times.



=== Bulk Operations

The {cpp} source repo contains an example of 
https://github.com/couchbase/couchbase-cxx-client/blob/{sdk_current_version}/examples/bulk_base_api.cxx[implementing a bulk get].
Careful benchmarking wwould be required to ensure that this approach is beneficial for your particular workload.
