= Using Couchbase Transactions
:description: A practical guide on using Couchbase Distributed ACID transactions, via the {cpp} SDK.
:page-partial:
:page-aliases: cxx-txns:ROOT:distributed-acid-transactions-from-the-sdk.adoc,cxx-txns:ROOT:distributed-transactions-cxx-release-notes.adoc
// :page-aliases: acid-transactions
:page-toclevels: 2
// :page-pagination: next

:lang: C++
:example-source: devguide:example$cxx/src/transactions.cxx
:example-source-lang: c++

include::partial$acid-transactions-attributes.adoc[]

[abstract]
{description}

This guide will show you examples of how to perform multi-document ACID (atomic, consistent, isolated, and durable) database transactions within your application, using the Couchbase Scala SDK.

Refer to the xref:concept-docs:transactions.adoc[] page for a high-level overview.

== Prerequisites

[{tabs}]
====
Couchbase Capella::
+
--
* Couchbase Capella account.
* You should know how to perform xref:howtos:kv-operations.adoc[key-value] or xref:howtos:sqlpp-queries-with-sdk.adoc[query] operations with the SDK.
* Your application should have the relevant roles and permissions on the required buckets, scopes, and collections, to perform transactional operations.
Refer to the xref:cloud:organizations:organization-projects-overview.adoc[Organizations & Access] page for more details.
* If your application is using xref:concept-docs:xattr.adoc[extended attributes (XATTRs)], you should avoid using the XATTR field `txn` -- this is reserved for Couchbase use.
--

Couchbase Server::
+
--
* Couchbase Server (6.6.1 or above).
* You should know how to perform xref:howtos:kv-operations.adoc[key-value] or xref:howtos:sqlpp-queries-with-sdk.adoc[query] operations with the SDK.
* Your application should have the relevant roles and permissions on the required buckets, scopes, and collections, to perform transactional operations.
Refer to the xref:{version-server}@server:learn:security/roles.adoc[Roles] page for more details.
* If your application is using xref:concept-docs:xattr.adoc[extended attributes (XATTRs)], you should avoid using the XATTR field `txn` -- this is reserved for Couchbase use.
* NTP should be configured so nodes of the Couchbase cluster are in sync with time.
--
====

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=requirements]

== Creating a Transaction

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=creating]

You can create transactions either _synchronously_ or _asynchronously_ using a callback-based API.

[{tabs}]
====
Synchronous API::
+
--
The synchronous mode is the easiest to write and understand.

Transactions are accessed via the `cluster` object.
By invoking `cluster.transactions()`, we can access the `transactions` object and `run` a transaction.

[source,{example-source-lang}]
----
include::{example-source}[tag=examples,indent=0]
----
--

Asynchronous API::
+
--
The asynchronous mode allows you to build your application in a reactive style, which can help you scale with excellent efficiency.

Transactions are accessed via the `ReactiveCluster` object.
By invoking `Cluster.reactive().transactions()`, we can access the `ReactiveTransactions` object and `run` the {lambda}.

[source,{example-source-lang}]
----
include::{example-source}[tag=examples-async,indent=0]
----
--
====

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=lambda-ctx]

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=creating-error]

== Key-Value Operations

You can perform transactional database operations using familiar key-value CRUD methods:

* **C**reate - `ctx->insert()`

* **R**ead - `ctx->get()`

* **U**pdate - `ctx->replace()`

* **D**elete - `ctx->remove()`

[IMPORTANT]
====
As mentioned <<lambda-ops,previously>>, make sure your application uses the transactional key-value operations inside the {lambda} -- such as `ctx->insert()`, rather than `collection.insert()`.
====

=== Insert

To insert a document within a transaction {lambda}, simply call `ctx->insert()`.

[{tabs}]
====
Synchronous API::
+
--
[source,{example-source-lang}]
----
include::{example-source}[tag=insert,indent=0]
----
--

Asynchronous API::
+
--
[source,{example-source-lang}]
----
include::{example-source}[tag=insert-async,indent=0]
----
--
====

=== Get

To retrieve a document from the database you can call `ctx->get()`.

[source,{example-source-lang}]
----
include::{example-source}[tag=get,indent=0]
----

`ctx->get()` will return a `transaction_get_result` object, which is very similar to the `get_result` you are used to.

If the application needs to ignore or take action on a document not existing, it can handle the failure:

[source,{example-source-lang}]
----
include::{example-source}[tag=get-propagate-failure,indent=0]
----

Gets will "Read Your Own Writes", e.g. this will succeed:

[source,{example-source-lang}]
----
include::{example-source}[tag=get-ryow,indent=0]
----

Of course, no other transaction will be able to read that inserted document, until this transaction reaches the commit point.

=== Replace

Replacing a document requires a `ctx->get()` call first.
This is necessary so the SDK can check that the document is not involved in another transaction, and take appropriate action if so.

[{tabs}]
====
Synchronous API::
+
--
[source,{example-source-lang}]
----
include::{example-source}[tag=replace,indent=0]
----
--

Asynchronous API::
+
--
[source,{example-source-lang}]
----
include::{example-source}[tag=replace-async,indent=0]
----
--
====

=== Remove

As with replaces, removing a document requires a `ctx->get()` call first.

[{tabs}]
====
Synchronous API::
+
--
[source,{example-source-lang}]
----
include::{example-source}[tag=remove,indent=0]
----
--

Asynchronous API::
+
--
[source,{example-source-lang}]
----
include::{example-source}[tag=remove-async,indent=0]
----

====

== {sqlpp} Queries

If you already use https://www.couchbase.com/products/n1ql[{sqlpp} (formerly N1QL)], then its use in transactions is very similar.
A query returns a `transaction_query_result` that is very similar to the `query_result` you are used to, and takes most of the same options.

[IMPORTANT]
====
As mentioned <<lambda-ops,previously>>, make sure your application uses the transactional query operations inside the {lambda} -- such as `ctx->query()`, rather than `cluster.query()` or `scope.query()`.
====

Here is an example of selecting some rows from the `travel-sample` bucket:

[source,{example-source-lang}]
----
include::{example-source}[tag=query-select-scope,indent=0]
----

An example using a `scope` for an `UPDATE`:

[source,{example-source-lang}]
----
include::{example-source}[tag=query-update,indent=0]
----

And an example combining `SELECT` and `UPDATE`.

[source,{example-source-lang}]
----
include::{example-source}[tag=query-complex,indent=0]
----

As you can see from the snippet above, it is possible to call regular C++ functions from the {lambda}, permitting complex logic to be performed.
Just remember that since the {lambda} may be called multiple times, so may the method.

Like key-value operations, queries support "Read Your Own Writes".
This example shows inserting a document and then selecting it again:

[source,{example-source-lang}]
----
include::{example-source}[tag=query-insert,indent=0]
----

<1> The inserted document is only staged at this point, as the transaction has not yet committed. +
Other transactions, and other non-transactional actors, will not be able to see this staged insert yet.
<2> But the `SELECT` can, as we are reading a mutation staged inside the same transaction.

== Mixing Key-Value and {sqlpp}

Key-Value and {sqlpp} query operations can be freely intermixed, and will interact with each other as you would expect.
In this example we insert a document with a key-value operation, and read it with a `SELECT` query.

[source,{example-source-lang}]
----
include::{example-source}[tag=query-kv-mix,indent=0]
----

<1> The key-value insert operation is only staged, and so it is not visible to other transactions or non-transactional actors.
<2> But the `SELECT` can view it, as the insert was in the same transaction.

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=rbac]

== Concurrent Operations

The async API allows operations to be performed concurrently inside a transaction, which can assist performance.

An example of performing parallel operations using the async API:

[source,{example-source-lang}]
----
include::{example-source}[tag=concurrent-ops,indent=0]
----

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=query-perf-note]

=== Non-Transactional Writes

To ensure key-value performance is not compromised, and to avoid conflicting writes, applications should *never* perform non-transactional _writes_ concurrently with transactional ones, on the same document.

The event contains the key of the document involved, to aid the application with debugging.

See xref:concept-docs:transactions.adoc#concurrency-with-non-transactional-writes[Concurrency with Non-Transactional Writes] to learn more.

== Configuration

The default configuration should be appropriate for most use-cases.
If needed, transactions can be globally configured at the point of creating the `cluster`:

[source,{example-source-lang}]
----
include::{example-source}[tag=config,indent=0]
----

include::{version-common}@sdk:shared:partial$acid-transactions.adoc[tag=config]

== Additional Resources

* Learn more about xref:concept-docs:transactions.adoc[Distributed ACID Transactions].

* Check out the SDK https://docs.couchbase.com/sdk-api/couchbase-cxx-client/namespacecouchbase_1_1transactions.html[API Reference].
