= Field Level Encryption from the SDK
:description: The Field Level Encryption library enables encryption and decryption of JSON fields, to support FIPS-140-2 compliance.
:page-edition: Enterprise Edition
// :page-aliases: ROOT:encrypting-using-sdk.adoc

:lang: C++
:example-source: devguide:example$cxx/src/field_level_encryption.cxx
:example-source-lang: c++

[abstract]
{description}

For a high-level overview of this feature, see xref:concept-docs:encryption.adoc[].

[#package]
== Packaging


The Couchbase {cpp} SDK works together with the https://github.com/couchbase/couchbase-cxx-encryption[{cpp} Couchbase Encryption^] library to provide support for encryption and decryption of JSON Object fields.
This library makes use of the cryptographic algorithms available on the OpenSSL or BoringSSL libraries linked to the {cpp} SDK, and provides a framework for implementing your own crypto components.

NOTE: The encryption code is packaged as an optional library and is subject to the Couchbase https://www.couchbase.com/LA03012021[License] and https://www.couchbase.com/ESLA08042020[Enterprise Subscription License] agreements.
To use the encryption library, you have to explicitly include this dependency in your project configuration.

To get started with the C++ Field Level Encryption library you can fetch it, for example, using https://github.com/cpm-cmake/CPM.cmake[CPM.cmake]:

[source,cmake]
----
CPMAddPackage(
  NAME
  couchbase_cxx_encryption
  GIT_TAG
  ${version}
  VERSION
  ${version}
  GITHUB_REPOSITORY
  "couchbase/couchbase-cxx-encryption")
----

=== Requirements
* Couchbase C++ SDK version `1.2.0` or later.
* C++ Couchbase Encryption version `1.0.0` or later.


== Configuration

To enable Field-Level Encryption, supply a `couchbase::crypto::manager` when xref:managing-connections.adoc#cluster-environment[configuring the C++ SDK's `couchbase::cluster_options`].

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=cluster_options]
----


== Usage

Two modes of operation are available out of the box using the provided `couchbase::crypto::default_transcoder`:

* Transparent encryption/decryption by defining which fields are to be encrypted for a custom document type.
* Manually specifying fields to be encrypted using `couchbase::crypto::document`.

NOTE: Only fields of JSON Objects can be encrypted.

=== Custom document type example

Sensitive fields of your data classes can be enumerated in an `encrypted_fields` static `std::vector<couchbase::crypto::encrypted_field>`. 
For each field, the name of the field, as it appears in the serialized JSON document, and optionally an encrypter alias should be specified.

[source,{example-source-lang}]
----
include::{example-source}[tag=person_struct,indent=0]
----

Now let's create a `person` document and save it to Couchbase:

IMPORTANT: Remember to use a crypto transcoder, such as `couchbase::crypto::default_transcoder`, when field encryption is required.

[source,{example-source-lang}]
----
include::{example-source}[tag=person_upsert,indent=0]
----

You can get the document as a `tao::json::value` and the default JSON transcoder to verify the field was encrypted:

[source,{example-source-lang}]
----
include::{example-source}[tag=person_get,indent=0]
----

Because the default JSON transcoder does not decrypt anything, the expected output is something like:

[source,json]
----
include::{example-source}[tag=encrypted_document,indent=0]
----

Now let's read the `person` document using the crypto transcoder:

[source,json]
----
include::{example-source}[tag=person_get_decrypt,indent=0]
----

This outputs the decrypted contents of the document:

[source,console]
----
include::{example-source}[tag=decrypted_document,indent=0]
----

=== `couchbase::crypto::document` example

If you need more control of which fields get decrypted, or if you prefer working with generic JSON types (such as `tao::json::value`),
you can use a `couchbase::crypto::document` instance and manually specify which fields to encrypt.

First, create a `couchbase::crypto::document<tao::json::value>` instance and specify the fields to encrypt. Then upsert the document to Couchbase:

[source,{example-source-lang}]
----
include::{example-source}[tag=crypto_doc_upsert,indent=0]
----

As before, you can get the document as a `tao::json::value` and the default JSON transcoder to verify the field was encrypted:

[source,{example-source-lang}]
----
include::{example-source}[tag=crypto_doc_get,indent=0]
----

This outputs the encrypted content of the document:

[source,{example-source-lang}]
----
include::{example-source}[tag=encrypted_crypto_doc,indent=0]
----

Now let's read the document using the crypto transcoder:

[source,json]
----
include::{example-source}[tag=crypto_doc_get_decrypt,indent=0]
----

This outputs the decrypted of the document:

[source,json]
----
include::{example-source}[tag=decrypted_crypto_doc,indent=0]
----

== Further Reading

* For a more detailed description of the C++ Encryption library's API, and additional examples, see the https://docs.couchbase.com/sdk-api/couchbase-cxx-encryption-1.0.0/index.html[API reference].
