= Search
:description: You can use the Search service to create queryable Search indexes in Couchbase Server.
:page-pagination: full
:page-toclevels: 2
:lang: C++
:example-source: devguide:example$cxx/src/search.cxx
:example-source-lang: c++


[abstract]
{description}

// add scoring note on https://docs.couchbase.com/server/current/release-notes/relnotes.html#known-issues-761 

The Search Service allows you to create, manage, and query Search indexes on JSON documents stored in Couchbase buckets. 
It uses natural language processing for querying documents, provides relevance scoring on the results of your queries, and has fast indexes for querying a wide range of possible text searches.
The supported query types include queries like Match and Term queries, range queries like Date Range and Numeric Range, compound queries for conjunctions, disjunctions, and boolean queries.
The Scala SDK exposes an API for performing Search queries which abstracts some of the complexity of using the underlying REST API.

== Examples
The examples below use these imports:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=imports]
----

Search queries are executed at Cluster level (not bucket or collection).
Here is an example match_query that looks for the text 'swanky' using a defined index:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=match_query]
----

[TIP]
.Search Results Limit
====
By default, the Search Service returns only the first 10 matches (`size: 10`, `from: 0`).
To retrieve more results, you must explicitly define pagination settings such as `size` or `from` in your query.

For information about formatting your Search query and specifying limits, see xref:server:search:search-request-params.adoc[].

For information about pagination in Search responses, see xref:server:fts:fts-search-response.adoc#pagination[Pagination].
====

All the query types are created in the same manner.
Some have additional properties, which can be seen in common query type descriptions.
Couchbase Search Service xref:{version-server}@server:fts:fts-query-types.adoc[range of query types] enable powerful searching using multiple options, to ensure results are just within the range wanted.

== Working with Results

The result of a Search query has 3 components: rows, facets, and metadata.
Rows are the documents that match the query.
Facets allow the aggregation of information collected on a particular result set.
Metadata holds additional information not directly related to your query, such as total rows and how long the query took to execute in the cluster.

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=working_with_results]
----


== Consistency

Like the Couchbase Query Service, the Search Service allows provides optional _Read-Your-Own-Writes (RYOW)_ consistency, ensuring results contain information from updated indexes:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=consistency]
----
