= Data Operations
:description: Data service offers the simplest way to retrieve or mutate data where the key is known. Here we cover CRUD operations, document expiration, and optimistic locking with CAS.
:page-aliases: document-operations.adoc
:page-toclevels: 2
:lang: C++
:example-source: devguide:example$cxx/src/kv_operations.cxx
:example-source-lang: c++

[abstract]
{description}
Here we cover CRUD operations, document expiration, and optimistic locking with CAS.

At its heart Couchbase Server is a high-performance key-value store, and the key-value interface outlined below is the fastest and best method to perform operations involving single documents.

A _document_ refers to an entry in the database (other databases may refer to the same concept as a _row_).
A document has an ID (_primary key_ in other databases), which is unique to the document and by which it can be located.
The document also has a value which contains the actual application data.
See xref:concept-docs:documents.adoc[the concept guide to _Documents_] for a deeper dive into documents in the Couchbase Data Platform.

Before proceeding, make sure you're familiar with the basics of authorization and connecting to a Cluster from the xref:hello-world:start-using-sdk.adoc[Start Using the SDK] section.

The code samples below will use these imports:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=imports]
----

[TIP]
The Query Service can also be used to perform many single-document operations, but we very strongly recommend using the key-value API for this instead.  It can be much more efficient as the request can go directly to the correct node, there's no query parsing overhead, and it's over the highly optimized memcached binary protocol.

== JSON

////


=== JSON

Now we can do some simple Key Value operations.  First, let's create some JSON.

The Scala SDK directly supports several popular JSON libraries, including https://github.com/lihaoyi/upickle[uPickle/uJson], https://circe.github.io/circe/[Circe], https://github.com/playframework/play-json[Play Json], https://github.com/typelevel/jawn[Jawn], and https://github.com/json4s/json4s[Json4s] (if you'd like to see your favorite supported, please let us know).
In addition you can supply JSON encoded into a `String` or `Array[Byte]`, opening the door to any JSON library; https://jsoniter.com/[Jsoniter] and https://github.com/FasterXML/jackson[Jackson] have been tested this way, but any should work.

You can also directly encode and decode Scala case classes to and from the SDK.

To make things easy and to help get you started, the Scala SDK also bundles a home-grown small JSON library, which you are free to use instead of or alongside any of the other supported JSON libraries.
The philosophy behind this library is to provide a very easy-to-use API and the fastest JSON implementation possible.

These options are described in detail xref:howtos:json.adoc[here], but to get us started let's created some simple JSON using the built-in JsonObject library:

[source,scala]
----
include::devguide:example$scala/Cloud.scala[tag=json,indent=0]
----

////

The Couchbase Server is a key-value store that's agnostic to what's stored, but it's very common to store JSON so most of the examples below will focus on that use-case.

The SDK directly supports the https://github.com/taocpp/json[taoJSON] library, which we'll be using for these examples. taoJSON also provides the ability to encode or decode user-defined types.

In addition you can supply and receive JSON as a `std::string` or `std::vector<std::byte>`, opening the door to any JSON library.

Support for other JSON libraries can also be added by defining your own custom JSON serializers, which is described in more detail in xref:json.adoc[this guide].

== Upsert
Here is a simple upsert operation, which will insert the document if it does not exist, or replace it if it does.

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=upsert]
----

[NOTE]
=====
All of the examples here use the simplest of the two asynchronous APIs provided by the C++ SDK, which returns an `std::future`.  There's also a callback-based asynchronous API. See xref:concurrent-async-apis[Choosing an API] for more details.
=====

The C++ SDK returns a `couchbase::error` instance that wraps an `std::error_code` rather than throwing exceptions. You can check whether an error occurred like this:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=upsert-error]
----

[NOTE]
We will use `fmt::println` to simply print any errors in these samples, but the application will of course want to perform better error handling.

== Insert
Insert works very similarly to upsert, but will fail if the document already exists:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=insert]
----


== Retrieving Documents

We've tried upserting and inserting documents into Couchbase Server, let's get them back:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=get-simple]
----


Of course if we're getting a document we probably want to do something with the content:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=get]
----

== Replace
A very common operation is to `get` a document, modify its contents, and `replace` it:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=replace]
----

There's a couple of things to cover with the `replace` line.

First, most of the methods in the C++ SDK take an 'options' parameter that contains optional parameters that have sensible defaults.  One of them, `cas`, is provided here.  We'll see more throughout this document.


[#optimistic-locking]
=== What is CAS?

CAS, or Compare and Swap, is a form of optimistic locking.  Every document in Couchbase has a CAS value, and it's changed on every mutation.  When you `get` a document you also get the document's CAS, and then when it's time to write the document, you send the same CAS back.  If another agent has modified that document, the Couchbase Server can detect you've provided a now-outdated CAS, and return an error instead of mutating the document.  This provides cheap, safe concurrency.  See xref:concurrent-document-mutations.adoc[this detailed description of CAS] for further details.

In general, you'll want to provide a CAS value whenever you `replace` a document, to prevent overwriting another agent's mutations.

=== Retrying on CAS Failures

But if we get a CAS mismatch, we usually just want to retry the operation.  Let's see a more advanced `replace` example that shows one way to handle this:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=replace-retry]
----


== Removing

Removing a document is straightforward:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=remove]
----

== Sub-Document Operations
All of the operations seen so far involve fetching the complete document.

As an optimization the application may consider using the xref:subdocument-operations.adoc[Sub-Document API] to access or mutate specific parts of a document.

== Durability

Writes in Couchbase are written initially to a single active node, and from there the Couchbase Server will take care of sending that mutation to any configured replicas.

The `durability` option, which all mutating operations accept, allows the application to wait until this replication is successful before proceeding.

It can be used like this:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=durability]
----

The default is `durability_level::none`, in which the SDK will return as soon as Couchbase Server has the mutation available in-memory on the active node.  This is the default for a reason: it's the fastest mode, and the majority of the time is all the application needs.

However, we recognize that there are times when the application needs that extra certainty that especially vital mutations have been successfully replicated, and the other durability options provide the means to achieve this.

The options differ depend on what Couchbase Server version is in use.  If 6.5 or above is being used, you can take advantage of the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[Durable Write] feature, in which Couchbase Server will only return success to the SDK after the requested replication level has been achieved.  The three replication levels are:

`majority` - The server will ensure that the change is available in memory on the majority of configured replicas.

`majority_and_persist_to_active` - Majority level, plus persisted to disk on the active node.

`persist_to_majority` - Majority level, plus persisted to disk on the majority of configured replicas.

The options are in increasing levels of failure-resistance.  Note that nothing comes for free - for a given node, waiting for writes to storage is considerably slower than waiting for it to be available in-memory.
These trade offs, as well as which settings may be tuned, are discussed in the xref:concept-docs:durability-replication-failure-considerations.adoc#durable-writes[durability page].


If a version of Couchbase Server lower than 6.5 is being used then the application can fall-back to xref:concept-docs:durability-replication-failure-considerations.adoc#older-server-versions['client verified' durability].
Here the SDK will do a simple poll of the replicas and only return once the requested durability level is achieved.  This can be achieved like this:

[source,{example-source-lang}]
----
include::{example-source}/[indent=0,tag=durability-observed]
----

To stress, durability is a useful feature but should not be the default for most applications, as there is a performance consideration, and the default level of safety provided by Couchbase will be resaonable for the majority of situations.


== Expiration/TTL








////
eventing is also a way to handle bulk deletes.  So is setting the expiration time.   If this is something like a daily purge, why not set the expiration time to the end of the day when the docs are being inserted?  If this is purging documents after they have been processed or transferred, why not delete (or expire) them as they are processed or transferred? (edited) 
////



Couchbase Server includes an option to have particular documents automatically expire after a set time.
This can be useful for some use-cases, such as user sessions, caches, or other temporary documents.

You can set an expiration value when creating a document:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=expiry-insert]
----

When getting a document, the expiry is not provided automatically by Couchbase Server but it can be requested:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=expiry-get]
----

Note that when updating the document, special care must be taken to avoid resetting the expiry to zero.  Here's how:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=expiry-replace]
----

Some applications may find `getAndTouch` useful, which fetches a document while updating its expiry field.  It can be used like this:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=expiry-get-and-touch]
----

include::{version-common}@sdk:shared:partial$documents.adoc[tag=exp-note]


// CAS
// https://www.couchbase.com/forums/t/how-many-leading-digits-of-the-cas-constitute-the-timestamp/32556/8
// not a guaranteed timestamp!



== Atomic Counter Operations

To support counter use-cases, a Couchbase document can be treated as an integer counter and adjusted or created atomically like this:

[source,{example-source-lang}]
----
include::{example-source}[indent=0,tag=counters]
----

Note that a counter cannot be below 0.

NOTE: Increment & Decrement are considered part of the ‘binary’ API and as such may still be subject to change

TIP: Setting the document expiry time only works when a document is created, and it is not possible to update the expiry time of an existing counter document with the Increment method -- to do this during an increment, use with the `Touch()` method.


// Atomicity Across Data Centers

include::{version-common}@sdk:shared:partial$atomic.adoc[tag=xdcr]


== Additional Resources

Working on just a specific path within a JSON document will reduce network bandwidth requirements - see the xref:subdocument-operations.adoc[Sub-Document] pages.

As well as various xref:concept-docs:data-model.adoc[Formats] of JSON, Couchbase can work directly with xref:concept-docs:nonjson.adoc[arbitrary bytes, or binary format].

Our xref:sqlpp-queries-with-sdk.adoc[Query Engine] enables retrieval of information using the SQL-like syntax of {sqlpp} (formerly N1QL).

