= Managing Connections
:description: This section describes how to connect the {name-sdk} to a Couchbase cluster.
// :page-aliases: ROOT:managing-connections,howtos:multi-network,ROOT:connecting,ROOT:connection-advanced
:page-toclevels: 2


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}
It contains best practices as well as information on TLS/SSL and advanced connection options, and a sub-page on troubleshooting Cloud connections.


Our xref:hello-world:start-using-sdk[Getting Started pages] cover the basics of making a connection to a Capella or self-managed Couchbase cluster.
This page is a wider look at the topic.


== Connecting to a Cluster


A connection to a Couchbase cluster -- on Capella, or self-managed -- is represented by a cluster object. 
A cluster provides access to buckets, scopes, and collections, as well as various Couchbase services and management interfaces. 
The simplest way to create a `cluster` object is to call `couchbase::cluster::connect()` with a connection string, username, and password:

[source,C++]
----
auto [cluster, ec] = couchbase::cluster::connect(io, connection_string, options).get();
----


And here it is in the context of a full connection lifecycle:

[source,C++]
----
#include <couchbase/cluster.hxx>
 
int
main(int argc, const char* argv[])
{
    if (argc != 4) {
        fmt::print("USAGE: ./start_using couchbase://127.0.0.1 Administrator password\n");
        return 1;
    }
 
    std::string connection_string{ argv[1] }; // "couchbase://127.0.0.1"
    std::string username{ argv[2] };          // "Administrator"
    std::string password{ argv[3] };          // "password"
    std::string bucket_name{ "travel-sample" };

    // run IO context on separate thread
    asio::io_context io;
    auto guard = asio::make_work_guard(io);
    std::thread io_thread([&io]() { io.run(); });
 
    auto options = couchbase::cluster_options(username, password);
    // customize through the 'options'.
    // For example, optimize timeouts for WAN
    options.apply_profile("wan_development");
 
    // [1] connect to cluster using the given connection string and the options
    auto [cluster, ec] = couchbase::cluster::connect(io, connection_string, options).get();
    if (ec) {
        fmt::print("unable to connect to the cluster: {}\n", ec.message());
        return 1;
    }
 
    // get a bucket reference
    auto bucket = cluster.bucket(bucket_name);
 
    // get a user-defined collection reference
    auto scope = bucket.scope("tenant_agent_00");
    auto collection = scope.collection("users");

    { // your database interactions here
    }
  
    // close cluster connection
    cluster.close();
    guard.reset();
 
    io_thread.join();
    return 0;
}
---- 


If this were compiled as `start_using`, then the connection string and authentication credentials would be passed as arguments to the command like so:

[source,console]
---- 
$ ./start_using couchbase://127.0.0.1 Administrator password
----

Here we're talking to a local development cluster.
For Capella, this will need `couchbases://` for TLS, followed by your Capella database name -- see xref:cloud:get-started:connect.adoc[].
The client certificate for connecting to Capella is included in the {name-SDK} installation.




== Connection Strings

A Couchbase connection string is a comma-delimited list of IP addresses and/or hostnames, optionally followed by a list of parameters.

The parameter list is just like the query component of a URI; name-value pairs have an equals sign (`=`) separating the name and value, with an ampersand (`&`) between each pair.
Just as in a URI, the first parameter is prefixed by a question mark (`?`).

.Simple connection string with one seed node
----
127.0.0.1
----

.Connection string with two seed nodes
----
nodeA.example.com,nodeB.example.com
----

.Connection string with two parameters
----
127.0.0.1?io.networkResolution=external&timeout.kvTimeout=10s
----

For the {cpp} SDK and its wrapper SDKs, this is the main method of passing client options, such as timout options or I/O options.
For more details see xref:ref:client-settings.adoc[], or the latest, complete listing in the 
// ###
[API Reference].



== Secure Connections



Couchbase Server Enterprise Edition and Couchbase Capella support full encryption of client-side traffic using Transport Layer Security (TLS). 

// min TLS version

// EE

// tls-no-verify vs ?

// auth page.






== Cloud Native Gateway


Couchbase's next generation connection protocol, introduced in Scala SDK 1.5 and Couchbase Autonomous Operator 2.6.1, can be enabled simply by changing the connection string to `couchbase2://` but there are a few differences to be aware of, described <<#limitations,below>>.
// Couchbase's next generation connection protocol, introduced in Scala SDK 1.5 and Couchbase Autonomous Operator 2.6.1, can be enabled simply by changing the connection string to `couchbase2://` but there are a few differences to be aware of, described <<#limitations,below>>.

The protocol implements a gRPC-style interface between the SDK and Couchbase Server (in this case, only available in the Server running on Kubernetes or OpenShift, with a forthcoming release of xref:operator::overview.adoc[Couchbase Autonomous Operator].



=== Limitations

The underlying protocol will not work with certain legacy features: MapReduce Views (a deprecated Service -- 
use xref:howtos:sqlpp-queries-with-sdk.adoc[Query] instead) and 
Memcached buckets (superseded by the improved xref:{server_version}@server:learn:buckets-memory-and-storage/buckets.adoc#bucket-types[Ephemeral Buckets]).

The following are not currently implemented over the `couchbase2://` protocol:

* Authentication by client certificate.
* Multi-document ACID transactions.
* Analytics service.
* Health Check.

There are some different behaviors seen with this protocol:

* Some config options are unsupported -- see the xref:ref:client-settings.adoc#cloud-native-gateway[Settings page].
* The SDK will poll the gRPC channels until they are in a good state, or return an error, or timeout while waiting -- in our standard protocol there is an option of setting `waitUntilReady()` for just certain services to become available.
* Some error codes are more generic -- in cases where the client would not be expected to need to take specific action -- but should cause no problem, unless you have written code looking at individual strings within the error messages.
* Although documents continue to be stored compressed by Couchbase Server, they will not be transmitted in compressed form (to and from the client) over the wire, using `couchbase2://`.




== Dealing With Network Latency






=== Working in the Cloud

// include::{version-common}@sdk:shared:partial$managing-connections.adoc[tag=cloud]


We strongly recommend that the client and server xref:project-docs:compatibility.adoc#network-requirements[are in the same LAN-like environment] (e.g. AWS Region).
As this may not always be possible during development, read the guidance on working with xref:ref:client-settings.adoc#commonly-used-options[constrained network environments].
More details on connecting your client code to Couchbase Capella can be found xref:cloud:clouds:connect-an-sdk.adoc#connecting-your-sdk-to-capella[in the Cloud docs].

// Add WAN profile info

IMPORTANT: If you are connecting from _IPv6-only_ environment, you cannot connect to Couchbase Capella as you are unable to use the IPv4 records published for Capella clusters.



==== Troubleshooting Connections to Cloud

Some DNS caching providers (notably, home routers) can’t handle an SRV record that’s large -- if you have DNS-SRV issues with such a set-up, reduce your DNS-SRV to only include three records.
[_For development only, not production._]. 
Our xref:troubleshooting-cloud-connections.adoc[Troubleshooting Cloud Connections] page will help you to diagnose this and other problems -- as well as introducing the SDK doctor tool.


== Complex Environments

== Alternate Addresses and Custom Ports



If your Couchbase Server cluster is running in a containerized, port mapped, or otherwise NAT’d environment like Docker or Kubernetes, 
a client running outside that environment may need additional information in order to connect the cluster. 
Both the client and server require special configuration in this case.



=== Using DNS SRV records

As an alternative to specifying multiple hosts in your program, you can get the actual bootstrap node list from a DNS SRV record. The following steps are necessary to make it work:

. Set up your DNS server to respond properly from a DNS SRV request.
. Enable it on the SDK and point it towards the DNS SRV entry.





////
== Next Steps

* xref:secure-connections.adoc[Certificate Authentication] 
////