= Metrics Reporting
:description: Individual request tracing presents a very specific (though isolated) view of the system.
:example-source-lang: c++



[abstract]
{description}

In the {name-sdk}, `couchbase::metrics::otel_meter` wraps an `opentelemetry::metrics::Meter`.

A complete code example showing how to instrument a Couchbase {cpp} application with `OpenTelemetry`, distributed tracing, and metrics, can be found https://github.com/couchbaselabs/couchbase-cxx-client-demo/blob/main/examples/inventory_with_opentelemetry.cpp[in our GitHub repo].
The snippets used on this page are taken from that example.


== Metrics Collection

The SDK's internal metric collection is activated with `options.metrics().enable(true)`:

[source,{example-source-lang}]
----
  options.metrics().enable(true);
  options.metrics().meter(std::make_shared<couchbase::metrics::otel_meter>(
    opentelemetry::metrics::Provider::GetMeterProvider()->GetMeter(k_service_name,
                                                                   k_service_version)));
----


The SDK reads the meter and tracer from the options object at connect time.
OTel metrics and tracing must be wired into cluster options before calling `couchbase::cluster::connect()`:

[source,{example-source-lang}]
----
  auto meter_provider = apply_opentelemetry_meter_options(options, config.metrics_config);
  auto tracer_provider = apply_opentelemetry_tracer_options(options, config.traces_config);

  auto [connect_err, cluster] =
    couchbase::cluster::connect(config.connection_string, options).get();
  if (connect_err) {
    std::cout << "Unable to connect to the cluster. ec: " << connect_err.message() << "\n";
  } else {
    auto collection = cluster.bucket(config.bucket_name)
                        .scope(config.scope_name)
                        .collection(config.collection_name);
----


== Exporting Metrics

In the example, the SDK records per-operation latency histograms and retry/timeout counters, all labelled by bucket, scope, collection, and operation type.
A `PeriodicExportingMetricReader` then pushes those measurements to the configured OTLP endpoint.

[source,{example-source-lang}]
----
  opentelemetry::sdk::metrics::PeriodicExportingMetricReaderOptions reader_options{};
  reader_options.export_interval_millis = metrics.reader_export_interval;
  reader_options.export_timeout_millis = metrics.reader_export_timeout;

  std::unique_ptr<opentelemetry::sdk::metrics::MetricReader> reader{
    new opentelemetry::sdk::metrics::PeriodicExportingMetricReader(std::move(exporter),
                                                                   reader_options)
----


.Complete tracing and metrics sample code: [*Click to open or collapse the listing*]
[%collapsible]
====
[source,{example-source-lang}]
----
include::devguide:example$cxx/src/inventory_with_opentelemetry.cpp[]
----
====




// Return to the below format with more info?

////
In addition, it also makes sense to capture information that aggregates request data (i.e. requests per second),
but also data which is not tied to a specific request at all (i.e. resource utilization).

The deployment situation itself is similar to the request tracer: either applications already have a metrics infrastructure in place or they don’t.
The difference is that exposing some kind of metrics is much more common than request based tracing,
because most production deployments at least monitor CPU and memory usage (e.g. through JMX).

Metrics broadly fall into the following categories:

* Request/Response Metrics (such as requests per second).
* SDK Metrics (such as how many open collections, various queue lengths).
* System Metrics (such as CPU usage or garbage collection performance).

Right now only the first category is implemented by the SDK; more are planned.


== The Default AggregatingMeter
[.status]#Developer Preview#

Before starting, here are all imports used in the following examples:

[source,scala]
----
include::devguide:example$scala/Metrics.scala[tag=imports,indent=0]
----

The default implementation aggregates and logs request and response metrics.
Since the feature is in developer preview, you need to manually enable it on the environment:

[source,scala]
----
include::devguide:example$scala/Metrics.scala[tag=metrics-enable,indent=0]
----

By default the metrics will be emitted every 10 minutes, but you can customize the emit interval as well:

[source,scala]
----
include::devguide:example$scala/Metrics.scala[tag=metrics-enable-custom,indent=0]
----

Once enabled, there is no further configuration needed.
The `AggregatingMeter` will emit the collected request statistics every interval.
A possible report looks like this (prettified for better readability):

[source,json]
----
{
   "meta":{
      "emit_interval_s":10
   },
   "query":{
      "127.0.0.1":{
         "total_count":9411,
         "percentiles_us":{
            "50.0":544.767,
            "90.0":905.215,
            "99.0":1589.247,
            "99.9":4095.999,
            "100.0":100663.295
         }
      }
   },
   "kv":{
      "127.0.0.1":{
         "total_count":9414,
         "percentiles_us":{
            "50.0":155.647,
            "90.0":274.431,
            "99.0":544.767,
            "99.9":1867.775,
            "100.0":574619.647
         }
      }
   }
}
----

Each report contains one object for each service that got used and is further separated on a per-node basis so they can be analyzed in isolation.

For each service / host combination, a total amount of recorded requests is reported, as well as percentiles from a histogram in microseconds.
The meta section on top contains information such as the emit interval in seconds, so tooling can later calculate numbers like requests per second.

The `AggregatingMeter` can be configured on the environment as shown above.
The following table shows the currently available properties:

.AggregatingMeterConfig Properties
[options="header"]
[cols="4,3,8"]
|===
| Property       | Default | Description

| `enabled`   | false | If the `AggregatingMeter` should be enabled.

| `emitInterval` | 600 seconds | The interval where found orphans are emitted.
|===


== OpenTelemetry Integration
[.status]#Developer Preview#

The SDK supports plugging in any `OpenTelemetry` metrics consumer instead of using the default `AggregatingMeter`.
To do this, first you need to add an additional dependency to your application:

[source,sbt]
----
libraryDependencies += "com.couchbase.client" % "metrics-opentelemetry" % "0.1.4"
----

Now you can initialise the SDK with OpenTelemetry:

[source,scala]
----
include::devguide:example$scala/Metrics.scala[tag=metrics-otel,indent=0]
----


== Micrometer Integration
[.status]#Developer Preview#

In addition to OpenTelemetry, we also provide a module so you can hook up the SDK metrics to Micrometer.

[source,xml]
----
libraryDependencies += "com.couchbase.client" % "metrics-micrometer" % "0.1.0"
----

In addition to the facade you also need to include your micrometer implementation of choice.
Once you've created the a Micrometer `MeterRegistry`, you need to wrap it and pass it into the environment:

[source,scala]
----
   val config: Try[ClusterEnvironment] = ClusterEnvironment.builder
      .meter(MicrometerMeter.wrap(meterRegistry))
      .build
----

At this point the metrics are hooked up to Micrometer and will be reported as `cb.requests` (as a `Counter`) and `cb.responses` (as a `DistributionSummary`).
////
