= Querying with {sqlpp}
:description: You can query for documents in Couchbase using the {sqlpp} query language, a language based on SQL, but designed for structured and flexible JSON documents.
:page-aliases: n1ql-query.adoc,n1ql-queries-with-sdk.adoc
// :page-aliases: ROOT:document-operations.adoc,ROOT:documents-creating,ROOT:documents-updating,ROOT:documents-retrieving,ROOT:documents-deleting,n1ql-queries-with-sdk.adoc
:lang: C++
:example-source: devguide:example$cxx/src/queries.cxx
:example-source-lang: c++

[abstract]
{description}



On this page we dive straight into using the Query Service API from the {name-sdk}.
For a deeper look at the concepts, to help you better understand the Query Service, the {sqlpp} language, and the Index Service,
see the links in the <<further-information,Further Information>> section at the end of this page.




Our query service uses {sqlpp}, which will be fairly familiar to anyone who's used any dialect of SQL.
<<Additional Resources>> for learning about {sqlpp} are listed at the end of this page.
Before you get started you may wish to checkout the xref:server:n1ql:n1ql-language-reference/index.adoc[{sqlpp} intro page].

[TIP]
.{sqlpp} Compared to Key-Value
====
{sqlpp} is excellent for performing queries against multiple documents, but if you only need to access or mutate a single document and you know its unique ID, it will be
much more efficient to use the Key-Value API.  We strongly recommend using both APIs to create a flexible, performant application.
====



== Getting Started
Let's get started by pulling in all the imports needed in the examples below:

[source,{example-source-lang}]
----
include::{example-source}[tag=imports,indent=0]
----

Then we connect to a Couchbase cluster, as usual (of course, change the address and credentials to match your own cluster's):

[source,{example-source-lang}]
----
include::{example-source}[tag=cluster,indent=0]
----

The examples below will use the travel-sample example bucket.  This can be installed through the Couchbase Admin UI in Settings -> Sample Buckets.

In order to be able to use query on a bucket, it must have at least a primary index created.  The easiest way to create this is
through the Couchbase Admin UI.  Simply visit the Query tab then write this in the Query Editor and hit Execute:

[source,n1ql]
----
CREATE PRIMARY INDEX ON `travel-sample`
----


// index first - start again - see both C++ and .NET versions....
// https://docs.couchbase.com/dotnet-sdk/current/howtos/n1ql-queries-with-sdk.html#querying-at-scope-level


Note that building indexes is covered in more detail on the xref:concept-docs:n1ql-query.adoc#index-building[Query concept page] --
and in the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/manager/query/index.html[API Reference].


== A Simple Query

Here's the basics of how to run a simple query to fetch 10 random rows from travel-sample and print the results:

[source,c++]
----
include::{example-source}/[tag=simple,indent=0]
----

(Note that we won't be covering the {sqlpp} language itself in any detail here, but if you're familiar with SQL you'll see it's very similar.)

The {cpp} SDK returns a `couchbase::error` instance that wraps an `std::error_code` rather than throwing exceptions.
You can check whether an error occurred like this:

[source,c++]
----
include::{example-source}/[tag=simple-results,indent=0]
----

The returned `query_result` contains an `rows_as<S,T>` method, allowing the results to be converted into something useful.
The above example demonstrates returning the results as a `tao::json::value` using the serializer `couchbase::codec::tao_json_serializer`, that uses the _taoJSON_ library.

In addition to `rows_as<S,T>` we provide accessors for common use cases like `rows_as_json` and `rows_as_binary`.

Please see xref:json.adoc[this guide] for more information on the supported ways of working with JSON.

The rows can be iterated as follows:

[source,c++]
----
include::{example-source}/[tag=get-rows,indent=0]
----

[NOTE]
=====
All of the examples here use the simplest of the two asynchronous APIs provided by the {cpp} SDK, which returns an `std::future`.  
There's also a callback-based asynchronous API. See xref:concurrent-async-apis[Choosing an API] for more details.
=====



== Placeholder and Named Arguments

Placeholders allow you to specify variable constraints for a query.

There are two variants of placeholders: positional and named parameters.  Both are used as placeholders for values in the WHERE, LIMIT or OFFSET clause of a query.

Positional parameters use an ordinal placeholder for substitution and can be used like this:

[source,{example-source-lang}]
----
include::{example-source}[tag=positional,indent=0]
----

Whereas named parameters can be used like this:

[source,{example-source-lang}]
----
include::{example-source}[tag=named,indent=0]
----



== Scan Consistency

Queries take an optional `scan_consistency` parameter that enables a tradeoff between latency and (eventual) consistency.

* A {sqlpp} query using the default `not_bounded` scan consistency will not wait for any indexes to finish updating before running the query and returning results, meaning that results are returned quickly, but the query will not return any documents that are yet to be indexed.

* With scan consistency set to `request_plus`, all outstanding document changes and index updates are processed before the query is run.
Select this when consistency is always more important than performance.

* For a middle ground, `at_plus` is a "read your own write" (RYOW) option, which means it just waits for the documents that you specify to be indexed.

Here's how to specify the `request_plus` scan consistency level:

[source,{example-source-lang}]
----
include::{example-source}[tag=request-plus,indent=0]
----




And the `at_plus` level is represented with `query_options.consistent_with()`:

[source,{example-source-lang}]
----
include::{example-source}[tag=at-plus,indent=0]
----


== Querying at Scope Level

// rearrange and put scope first????

It is possible to query off the xref:{version-common}@server:learn:data/scopes-and-collections.adoc[`scope` level] with _Couchbase Server version 7.0_ onwards,
using the `scope.query()` method.
It takes the statement as a required argument, and then allows additional options if needed.

The code snippet below shows how to run a simple query to fetch 10 rows from travel-sample and print the results,
the assumption is that the `airline` collection exists within the scope.

[source,{example-source-lang}]
----
include::{example-source}[tag=scope-level,indent=0]
----

// TODO: Insert link to API docs.
A complete list of `query_options` can be found in the https://docs.couchbase.com/sdk-api/couchbase-cxx-client/structcouchbase_1_1query__options.html[API docs].




== Additional Resources


NOTE: {sqlpp} is not the only query option in Couchbase.
Be sure to check that xref:concept-docs:data-services.adoc[your use case fits your selection of query service].

The http://query.pub.couchbase.com/tutorial/#1[{sqlpp} interactive tutorial] is a good introduction to the basics of {sqlpp} use.





// tutorial - https://query.pub.couchbase.com/tutorial/#1
// check it's working still?

// recursive
// https://www.couchbase.com/blog/recursive-query-processing-in-sql-n1ql/ 





// also
// query options
// https://github.com/couchbaselabs/sdk-rfcs/pull/125/files 



// == Further Information


