= Querying with {sqlpp}
:description: You can query for documents in Couchbase using the {sqlpp} query language, a language based on SQL, but designed for structured and flexible JSON documents.
:page-aliases: n1ql-query.adoc,n1ql-queries-with-sdk.adoc
// :page-aliases: ROOT:document-operations.adoc,ROOT:documents-creating,ROOT:documents-updating,ROOT:documents-retrieving,ROOT:documents-deleting,n1ql-queries-with-sdk.adoc
:lang: C++
:example-source: devguide:example$cxx/src/queries.cxx
:example-source-lang: c++

[abstract]
{description}



On this page we dive straight into using the Query Service API from the {name-sdk}.
For a deeper look at the concepts, to help you better understand the Query Service, the {sqlpp} language, and the Index Service,
see the links in the <<further-information,Further Information>> section at the end of this page.








include::howtos:partial$n1ql-intro.adoc[]
include::howtos:partial$n1ql-getting-started.adoc[]


// index first - start again - see both C++ and .NET versions....
// https://docs.couchbase.com/dotnet-sdk/current/howtos/n1ql-queries-with-sdk.html#querying-at-scope-level


Note that building indexes is covered in more detail on the xref:concept-docs:n1ql-query.adoc#index-building[Query concept page] --
and in the https://docs.couchbase.com/sdk-api/couchbase-scala-client/com/couchbase/client/scala/manager/query/index.html[API Reference].


== A Simple Query
Here's the basics of how to run a simple query to fetch 10 random rows from travel-sample and print the results:

[source,c++]
----
include::{example-source}/[tag=simple,indent=0]
----

(Note that we won't be covering the {sqlpp} language itself in any detail here, but if you're familiar with SQL you'll see it's very similar.)

The {cpp} SDK returns a `couchbase::error` instance that wraps an `std::error_code` rather than throwing exceptions.
You can check whether an error occurred like this:

[source,c++]
----
include::{example-source}/[tag=simple-results,indent=0]
----

The returned `query_result` contains an `rows_as<S,T>` method, allowing the results to be converted into something useful.
The above example demonstrates returning the results as a `tao::json::value` using the serializer `couchbase::codec::tao_json_serializer`, that uses the _taoJSON_ library.

In addition to `rows_as<S,T>` we provide accessors for common use cases like `rows_as_json` and `rows_as_binary`.

Please see xref:json.adoc[this guide] for more information on the supported ways of working with JSON.

The rows can be iterated as follows:

[source,c++]
----
include::{example-source}/[tag=get-rows,indent=0]
----

[NOTE]
=====
All of the examples here use the simplest of the two asynchronous APIs provided by the {cpp} SDK, which returns an `std::future`.  
There's also a callback-based asynchronous API. See xref:concurrent-async-apis[Choosing an API] for more details.
=====

include::howtos:partial$n1ql-placeholders.adoc[indent=0]
include::howtos:partial$n1ql-scan-consistency.adoc[indent=0]

And the `at_plus` level is represented with `query_options.consistent_with()`:

[source,{example-source-lang}]
----
include::{example-source}[tag=at-plus,indent=0]
----

== Querying at Scope Level

// rearrange and put scope first????

It is possible to query off the xref:7.1@server:learn:data/scopes-and-collections.adoc[`scope` level] with _Couchbase Server version 7.0_ onwards,
using the `scope.query()` method.
It takes the statement as a required argument, and then allows additional options if needed.

The code snippet below shows how to run a simple query to fetch 10 rows from travel-sample and print the results,
the assumption is that the `airline` collection exists within the scope.

[source,{example-source-lang}]
----
include::{example-source}[tag=scope-level,indent=0]
----

// TODO: Insert link to API docs.
A complete list of `query_options` can be found in the https://docs.couchbase.com/sdk-api/couchbase-cxx-client/structcouchbase_1_1query__options.html[API docs].


include::howtos:partial$n1ql-additional-resources.adoc[]

// tutorial - https://query.pub.couchbase.com/tutorial/#1
// check it's working still?

// recursive
// https://www.couchbase.com/blog/recursive-query-processing-in-sql-n1ql/ 





// also
// query options
// https://github.com/couchbaselabs/sdk-rfcs/pull/125/files 



== Further Information


