= Compatibility
:description: Platform compatibility, and features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 3
:table-caption!:


[abstract]
{description}


The Couchbase {cpp} SDK {sdk_dot_minor} Client supports {cpp} 17, or more recent versions.


== Platform Compatibility



=== OS Compatibility

In general, the SDK should run on any modern platform with the correct compiler and version of `cmake`,
and the Couchbase {cpp} SDK can be expected to run on all of the Operating Systems supported by xref:{version-server}@server:install:install-platforms.adoc[Couchbase Server].

The {name-sdk} is tested and supported on the following OSs and platforms:

****
[discrete]
=== GNU/Linux

* Amazon Linux 2 & AL2023.
* Red Hat Enterprise Linux 8, 9, & 10.
* Oracle Linux 8, 9, & 10.
* Ubuntu (LTS) 22.04 (_Jammy_) & 24.04 (_Noble_).
* Debian 11 (_Bullseye_), Debian 12 (_Bookworm_), & Debian 13 (_Trixie_).
* SUSE Enterprise Linux 12 & 15.
* Alpine Linux 3.21 - 3.23.

[discrete]
=== Microsoft Windows

* Microsoft Windows 10 & 11;
* Windows Server 2019, 2022, & 2025.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (August 2026): 26 (Tahoe), 15 (Sequoia), and 14 (Sonoma).
****

The SDK should also be expected to run on other commonly-available GNU/Linux distributions which support an appropriate compiler, but not all combinations can be tested.


////
 -- notable exceptions are listed below.

==== Alpine Linux Compatibility

The https://netty.io[Netty] I/O library used by our JVM SDKs supports native optimizations to achieve higher throughput and lower latency 
-- which the SDK enables by default. 
Those modules are compiled against `glibc` and Alpine Linux uses `musl` instead --
so the {name-sdk} is unable to complete bootstrapping on this platform.

Because Alpine Linux does not have the `glibc` support needed,
we highly recommend that you seek an alternative distribution where possible. 
If that is not a option, then a possible workaround that can be applied is as follows:

* Disable the native IO:
+
[source,toml]
====
ClusterEnvironment env = ClusterEnvironment.builder().ioEnvironment(IoEnvironment.enableNativeIo(false)).build();
====

* Disable it in Netty itself via the following system property:
`-Dcom.couchbase.client.core.deps.io.netty.transport.noNative=true`

The downside of these workarounds is potentially reduced performance, which can be determined through benchmarking and profiling.
////



// Platforms, Chipsets, and Virtual Environments.
include::{version-common}@sdk:shared:partial$platform.adoc[tag=virtual]



// Network Requirements
include::{version-common}@sdk:shared:partial$network-requirements.adoc[]






== Couchbase Server Compatibility


Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.

=== Couchbase Version/SDK Version Matrix

The matrix below denotes the version of Couchbase Server, the version of the {name-sdk} and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
evertheless, this combination is not recommended by our technical support organization, as not all of the latest features are supported by it.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
|===
| | 1.0 | 1.1 | 1.2, 1.3 | 1.4

| *Server 8.0* ①
| *✔*
| *✔*
| *✔*
| *✔*

| *Server 7.6* ①
| *✔*
| *✔*
| *✔*
| *✔*

| *Server 7.2*
| *◎*
| *◎*
| *✔*
| *✔*
|===


① Server 7.6 & 8.0 are compatible with all supported (not yet End-of-Life) versions of the {name-sdk}, but for full support of the latest features you need to upgrade to a recent version of the SDK.
See the <<#couchbase-new-feature-availability-matrix,Feature Availablity matrix below>> and the xref:sdk-release-notes.adoc[Release Notes page].

Note the https://www.couchbase.com/support-policy/EOL/[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.




=== Capella Compatibility

The Couchbase {name_platform} SDK is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the SDK includes the Capella client certificate ready installed.

include::{version-common}@sdk:shared:partial$capella.adoc[tag=cloud]


// add in Columnar link

=== Couchbase New Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells]
[cols="5,4,4,5,5"]
|===
| | Server 7.0 & 7.1 | Server 7.2 | Server 7.6  | Server 8.0

| Enhanced Durability
4+| All SDK versions

| Vector Search
2+| N/A
2+| From SDK 1.0.0

| Replica Reads
2+| N/A
2+| From SDK 1.0.0 -- _Preferred Server Group Replica Reads_ from Server 7.6.2 and SDK 1.0.0

| Response Time Observability
4+| From SDK 1.3.0
|===

This table is not an exhaustive list -- just a few highlights -- provided to help assess compatibility of older versions in particular.
For alignment of SDKs and new Server features, scroll down to the information below the <<api-version,API Version table>>.


=== API Version

include::{version-common}@sdk:shared:partial$api-version.adoc[tag=api-version]




== SDK API Stability


=== Interface Stability

include::{version-common}@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]


=== Older SDK Versions

include::{version-common}@sdk:shared:partial$archive.adoc[tag=link]
