= Compatibility of Couchbase Features, Couchbase Server Versions, and the Couchbase {name-sdk}
:description: Features available in different SDK versions, and compatibility between Server and SDK. \
Plus notes on Cloud, networks, and AWS Lambda.
:navtitle: Compatibility
// :page-aliases: ROOT:overview,ROOT:compatibility-versions-features,compatibility-versions-features
:page-toclevels: 2

include::project-docs:partial$preview-warning.adoc[]


// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.

[abstract]
{description}



// Awaiting heavy editing





The {name-sdk} is compatible with most modern {cpp} environments, and has the following buid dependencies:

* cmake >= 3.20.0+
* {cpp} compiler >= std_17
* openssl >= 1.1+


== Couchbase Version/SDK Version Matrix

Couchbase SDKs are tested against a variety of different environments to ensure both backward and forward compatibility with different versions of Couchbase Server.
The matrix below denotes the version of Couchbase Server, the version of the Java SDK and whether the SDK is:

* ✖ *Unsupported*: This combination is not tested, and is not within the scope of technical support if you have purchased a support agreement.
* ◎ *Compatible*: This combination has been tested previously, and should be compatible.
This combination is not recommended by our technical support organization.
It is best to upgrade either the SDK or the Couchbase version you are using.
* ✔ *Supported*: This combination is subject to ongoing quality assurance, and is fully supported by our technical support organization.

// consider carefully the 2.x/6.x for other SDKs, to help support calls.

.Recommended SDK per Server Version Matrix
[#table_sdk_versions]
[cols="40,50"]
|===
| | SDK 1.0

| *Server 7.0-7.2*
| *✔*
|===

////
| *Server 7.5-7.6*
| *✔*
|===
////

Note the https://www.couchbase.com/support-policy[End of Life dates^] for Couchbase Server and SDK versions.
See the notes there for Support details.

=== Capella Compatibility

The Couchbase {sdk_dot_minor} {name-sdk} is fully compatible with Couchbase Capella, our fully-hosted database-as-a-service.
To make development easier, the {sdk_dot_minor} SDK includes the Capella client certificate ready installed.

include::{version-server}@sdk:shared:partial$capella.adoc[tag=cloud]


== OS Compatibility

The Couchbase {name-sdk} is tested and supported on the following platforms:



****
[discrete]
=== GNU/Linux

* Amazon Linux 2 & AL2023.
* Red Hat Enterprise Linux 8 & 9;
// * Alma Linux 9, Rocky Linux 9.
* Ubuntu (LTS) 20.04 (_Focal_) & 22.04 (_Jammy_).
* Debian 10 (_Buster_) & 11 (_Bullseye_).
* Alpine Linux.

[discrete]
=== Microsoft Windows

Microsoft Windows 10 / All LTS releases from Windows Server 2019.

[discrete]
=== Mac OS X

The current and previous two releases of OS X.
At time of writing (November 2023): 14 (Sonoma), 13 (Ventura), and 12 (Monterey).
M1 ARM  architecture is fully supported in the {name-sdk}.
****

Although installable or compilable on many other platforms, we cannot provide support for untested combinations.

[discrete]
=== ARM Processor Support

AWS Amazon Graviton2, Apple M1 ARM processors, and ARMv8 on Ubuntu 20.04+ 
****


////
The {name-sdk} should also be expected to run on other commonly-available GNU/Linux distributions which support an appropriate {cpp} build environment, but not all combinations can be tested -- notable exceptions are listed below.

=== Alpine Linux Compatibility

The https://netty.io[Netty] I/O library used by our JVM SDKs supports native optimizations to achieve higher throughput and lower latency 
-- which the SDK enables by default. 
Those modules are compiled against `glibc` and Alpine Linux uses `musl` instead --
so the Java SDK is unable to complete bootstrapping on this platform.

Because Alpine Linux does not have the `glibc` support needed,
we highly recommend that you seek an alternative distribution where possible. 
If that is not a option, then a possible workaround that can be applied is as follows:

////

== Couchbase Feature Availability Matrix

.Couchbase Server and SDK Supported Version Matrix
[.table-merge-cells] 
[cols="7,5,5,5,7"]
|===
| | Server 7.0 - 7.2

| Enhanced Durability
| All SDK versions

| Durable Writes 
| All SDK versions

| Analytics
| All SDK versions

| DP in 5.5 with SDK 2.6
3+| Since SDK 2.7

| Distributed ACID Transactions
| All SDK versions

| N1QL Queries inside the Transaction Lambda
| All SDK versions

| Collections
| All SDK versions

| Scope-Level N1QL Queries & all Collections features
| All SDK versions

| Field Level Encryption v2
| All SDK versions

| Request Tracing
| All SDK versions
|===

////
include::{version-common}@sdk:shared:partial$network-requirements.adoc[]
////



== Network Requirements

Couchbase SDKs are developed to be run in an environment with local area network (LAN) like throughput and latencies.
While there is no technical issue that prevents the use across a wide area network (WAN), SDKs have certain thresholds around timeouts and behaviors to recover that will not be the same once the higher latency and possible bandwidth constraints and congestion of a WAN is introduced.
Couchbase tests for correctness under LAN like conditions.
For this reason, only LAN-like network environments are officially supported.

Couchbase does document, for purposes of convenience when developing and performing basic operational work, what may need to be tuned when network throughputs and latencies are higher.
If you encounter issues, even with these tune-ables, you should attempt the same workload from a supported, LAN-like environment.

=== Serverless Environments

SDK API 3.4 introduces better resilience in handling errors that may occur when running your application in serverless environments, in particular when processes are frozen or thawed, and a rebalance is required.
This means official support for AWS Lambda, Azure Functions, and GCP Functions.

NOTE: When *DNS SRV* records are used to connect to the SDK it is possible for the underlying addresses to change (i.e. the cluster could move).
The SDK will detect this and react accordingly so that your application can continue to work correctly.


//    ^ network requirements to common file



////
[#spring-compat]
== Spring Data Couchbase Compatibility

https://projects.spring.io/spring-data-couchbase/[Spring Data Couchbase^] uses the Java SDK underneath and as a result is also provides different compatibilities with Couchbase Server.
The following table provides an overview.

.Recommended Spring Data Couchbase per Server Version Matrix
[#table_spring_versions]
|===
|  | SDC 4.0 - 4.4

| _Status ->_
| _New Features, Active Development_

| *Server 6.0*
| *Recommended*

| *Server 6.5 & 6.6*
| *Recommended*

| *Server 7.0 & 7.1*
| *Recommended*
|===

NOTE: Check the Spring Data Couchbase's compile dependencies -- older versions may link an out-of-date version of the Java SDK in their dependencies list, although a supported version should be in the `updates`.
Please make sure that you are using a supported version of the Couchbase Java SDK, prefereably the latest version, which will contain any available bug fixes.
Using the latest Spring Data Couchbase should ensure that this is so.

[CAUTION]
.Reactor Core Version
====
SpringBoot may set the io.projectreactor version at an earlier version than the one needed by the current version of https://search.maven.org/artifact/com.couchbase.client/core-io/2.2.0/jar[Couchbase JVM Core IO]. 
In case of errors, override with Core IO's preferred version, e.g.:

----
<dependency>
    <groupId>io.projectreactor</groupId>
    <artifactId>reactor-core</artifactId>
    <version>3.4.6.RELEASE</version>
</dependency>
----
====
////


// include::7.1@sdk:shared:partial$interface-stability-pars.adoc[tag=interface-stability-section]
 
== Interface Stability

[#interface-stability-par]
// tag::interface-stability-par[]
Couchbase SDKs indicate the stability of an API through documentation.
Since there are different meanings when developers mention stability, we mean *interface stability*: how likely the interface is to change or be removed entirely.
A stable interface is one that is guaranteed not to change between versions, meaning that you may use an API of a given SDK version and be assured that the given API will retain the same parameters and behavior in subsequent versions.
An unstable interface is one which may appear to work or behave in a specific way within a given SDK version, but may change in its behavior or arguments in future SDK versions, causing odd application behavior or compiler/API usage errors.
*Implementation stability* is implied to be more reliable at higher levels, but all are tested to the level that is appropriate for their stability.
// end::interface-stability-par[]

Couchbase uses three interface stability classifiers.
You may find these classifiers appended as annotations or comments within documentation for each API:

* *Committed*: This stability level is used to indicate the most stable interfaces that are guaranteed to be supported and remain stable between SDK versions.
This is the default -- unless otherwise stated in the documentation, each API has *Committed* status.
* *Uncommitted*: This level is used to indicate APIs that are _unlikely_ to change, but _may_ still change as final consensus on their behavior has not yet been reached.
_Uncommitted_ APIs usually end up becoming stable APIs.
* *Volatile*: This level is used to indicate experimental APIs that are still in flux and may likely be changed.
It may also be used to indicate inherently private APIs that may be exposed, but "YMMV" (your mileage may vary) principles apply.
_Volatile_ APIs typically end up being promoted to _Uncommitted_ after undergoing some modifications.

APIs that are marked as _Committed_ have a stable implementation.
_Uncommitted_ and _Volatile_ APIs should be stable within the bounds of any known and often documented issues, but Couchbase has not made a commitment to these APIs and may not respond to reported defects with the same priority.

Additionally, take note of the following interface labels:

* *Deprecated*: Any API marked deprecated may be removed in the next major version released. 
Couchbase recommends migrating from the deprecated API to the replacement as soon as possible. 
In rare instances, deprecated API may be rendered non-functional in a dot-minor release when the API cannot continue to be supported.
* *Internal*: This level is used to indicate you should not rely on this API as it is not intended for use outside the module, even to other Couchbase components.


// include::7.1@sdk:shared:partial$api-version.adoc[tag=api-version]




== API Version

This release of the SDK is written to version 3.4 of the SDK API specification (and matching the features available in Couchbase 7.2 and earlier).
For most developers, just using the latest version will be all that matters, and few will need to look at another of our SDKs.
Just for those few that do, the table below shows each Couchbase SDK release version that matches the API version.

Whilst these two numbers match for the .NET, Java, and Ruby SDKs, this is not the case for the others, as version numbers for individual SDKs are bumped up in line with https://semver.org/[Semantic Versioning] -- check the xref:sdk-release-notes[release notes] of each SDK for individual details.

.SDK API Versions
[cols="40,20,20,25,20,20,20"]
|===
| | API 3.0 | API 3.1 | API 3.2 | API 3.3 | API 3.4 | API 3.5

| C (libcouchbase)
| 3.0
| 3.1
| 3.2
| 3.3.0 - 3.3.2
| 3.3.3 footnote:[Excludes DNS SRV refresh support in Serverless Environments.]
| 3.??

| .NET
| 3.0
| 3.1
| 3.2
| 3.3
| 3.4
| 3.5

| Go
| 2.0 & 2.1
| 2.2
| 2.3 & 2.4
| 2.5
| 2.6 & 2.7
| 2.8

| Java
| 3.0
| 3.1
| 3.2
| 3.3
| 3.4 & 3.5
| 3.6

| Kotlin
| -
| -
| -
| 1.0
| 1.1 & 1.2
| 1.3

| Node.js
| 3.0
| 3.1
| 3.2 & 4.0
| 4.1
| 4.2
| 4.3

| PHP
| 3.0
| 3.1
| 3.2
| 4.0
| 4.1
| 4.2

| Python
| 3.0
| 3.1
| 3.2
| 4.0
| 4.1
| 4.2

| Ruby
| 3.0
| 3.1
| 3.2
| 3.3
| 3.4
| 3.5

| Scala
| 1.0
| 1.1
| 1.2
| 1.3
| 1.4 & 1.5
| 1.6
|===


*SDK API 3.5*: Introduced Faster Failover and KV Range Scan.

*SDK API 3.4*: Introduced support for ARM v8 on Ubuntu 20.04, Transactions on Spring Data Couchbase, and compatibility with running in serverless environments, such as AWS λ.
Protostellar was introduced in Go 2.7, for xref:operator::overview.adoc[Couchbase Autonomous Operator] 2.6.

*SDK API 3.3*: Introduced alongside Couchbase Server 7.1, adds Management API for Eventing and Index Management for Scopes & Collections; extends Bucket Management API to support Custom Conflict Resolution and Storage Options; adds new platform support for Linux Alpine OS, Apple M1, and AWS Graviton2; provides improved error messages for better error handling. and an upgraded Spark Connector that runs on Spark 3.0 & 3.1 Platform.

*SDK API 3.2*: Introduced alongside Couchbase Server 7.0, provides features in support of Scopes and Collections, extends capabilities around Open Telemetry API to instrument telemetry data, enhanced client side field level encryption to add an additional layer of security to protect sensitive data, adds new platform support such as Ubuntu 20.04 LTS.

*SDK API 3.1*: Introduced alongside Couchbase Server 6.6,  focuses on Bucket Management API, adds capabilities around Full Text Search features such-as  Geo-Polygon support, Flex Index, and Scoring. 

*SDK API 3.0*: Introduced alongside Couchbase Server 6.5,  is a major overhaul from its predecessor, has simplified surface area, removed long-standing bugs and deprecated/removed old API, introduces new programming languages Scala and Ruby, written in anticipation to support Scopes and Collections.




// include::7.1@sdk:shared:partial$archive.adoc[tag=link]

////
[.column]
====== {empty}

== Older SDK Versions

Documentation on older, unsupported versions of the SDK -- that have reached end-of-life -- can be found in the https://docs-archive.couchbase.com/home/index.html[archive].
////