= Full Installation of the {cpp} SDK
:description: Installation instructions for the Couchbase Scala Client.
:navtitle: Full Installation
:page-partial:
:page-toclevels: 2

// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}




This page gives full installation instructions for the {name-sdk}.
In most cases, the xref:hello-world:start-using-sdk.adoc[Quickstart Guide] should be enough to get you up and running if you're in a hurry.


== Prerequisites



=== Getting the Source Code

This repo uses several git submodules. If you are fetching the repo for the first time by command line, the `--recurse-submodules` option will init the submodules recursively as well:

[source,console]
----
git clone --recurse-submodules https://github.com/couchbaselabs/couchbase-cxx-client.git
----

However, if you fetched using a simple clone command (or another IDE or tool) you must also perform the following command to recursively update and initialize the submodules:

[source,console]
----
git submodule update --init --recursive
----

=== Building with CMake

This repo is being built with CMake so everything should build easily once the basic dev dependencies are satisfied.

=== Dev Dependencies

The following dependencies must be installed before the project can be built. We recommend using OS specific utilities such as brew, apt-get, and similar package management utilities (depending on your environment).

====
cmake >= 3.20.0+ (e.g., brew install cmake)
c++ compiler >= std_17 (e.g., xcode-select --install)
openssl >= 1.1+ (e.g., brew install openssl)
====

IMPORTANT: On macOS, the OpenSSL brew install command mentioned above is not sufficient to be able to build. 
The easiest way to fix this is to add the `OPENSSL_ROOT_DIR` env variable to your exports (e.g., .zshenv). 
If this is not sufficient, see the other tips mentioned when you run brew info openssl.

[source,console]
----
export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ 
----

=== Building (command-line)

[source,console]
----
$ cd couchbase-cxx-client
----

[source,console]
----
$ mkdir build; cd build
----

[source,console]
----
$ cmake ..
----

[source,console]
----
$ cmake --build
----

// Node - https://www.couchbase.com/forums/t/build-of-node-js-sdk-4-2-6-fail-on-debian-11-bullseye/36792/6 
