= SDK Release Notes
:description: Release notes, brief installation instructions, and download archive for the Couchbase {cpp} Client.
:navtitle: Release Notes
:page-toclevels: 2
// :page-aliases: relnotes-cxx-sdk

// tag::all[]
[abstract]
{description}

Version {sdk_dot_minor} of the {cpp} SDK implements the {sdk_api} xref:compatibility.adoc#api-version[SDK API].
See the xref:compatibility.html#couchbase-feature-availability-matrix[compatibility pages] for more information on feature compatibility with different versions of Couchbase Server.


== Installation


=== Prerequisites

Check that you have the dependencies installed:

* cmake >= 3.20.0+ (e.g., `brew install cmake`)
* c++ compiler >= std_17 (e.g., `xcode-select --install`)
* openssl >= 1.1+ (e.g., `brew install openssl`)

Supprted Operating Systems are listed on the xref:project-docs:compatibility.adoc#platform-compatibility[compatibility page].


=== GNU/Linux Installation

More details of the installation process, and extra steps required for openssl build, can be found in the xref:project-docs:sdk-full-installation.adoc[full installation guide].
On most GNU/Linux platforms at least, installation is a matter of:

[source,console]
----
$ git clone --recurse-submodules https://github.com/couchbaselabs/couchbase-cxx-client.git
----

[source,console]
----
$ export OPENSSL_ROOT_DIR=/usr/local/opt/openssl/ 
----

.Building (command-line)
[source,console]
----
$ cd couchbase-cxx-client
----

[source,console]
----
$ mkdir build; cd build
----

[source,console]
----
$ cmake ..
----

[source,console]
----
$ cmake --build .
----





// reminder - add spoiler tag to wrappers for cxx notes?



[#latest-release]
== {cpp} SDK 1.0 Releases

We always recommend using the latest version of the SDK -- it contains all of the latest security patches and support for new and upcoming features.
All patch releases for each dot minor release should be API compatible, and safe to upgrade;
any changes to expected behavior are noted in the release notes that follow.





== Older Versions

Release Notes for the developer preview releases before the 1.0.0 release can be found on {sdk-gh-link}releases[GitHub].
