= Full Installation of the {cpp} SDK
:description: Installation instructions for the Couchbase {cpp} Client.
:navtitle: Full Installation
:page-partial:
:page-toclevels: 2

// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}

This page gives full installation instructions for the {name-sdk}.
In most cases, the xref:hello-world:start-using-sdk.adoc[Quickstart Guide] should be enough to get you up and running if you're in a hurry.

== Prerequisites

A {cpp} 17 compiler and https://cmake.org/[CMake] version 3.19 or newer is required. See the xref:project-docs:compatibility.adoc[Compatibility] section for details on supported platforms.

== Installing the SDK

=== With CPM.cmake

https://github.com/cpm-cmake/CPM.cmake[CPM.cmake] makes it really easy to include the library in your project. You only need to include the following command in your `CMakeLists.txt`.

[source,cmake]
----
CPMAddPackage(
  NAME
  couchbase_cxx_client
  GIT_TAG
  1.0.0
  VERSION
  1.0.0
  GITHUB_REPOSITORY
  "couchbase/couchbase-cxx-client"
  OPTIONS
  "COUCHBASE_CXX_CLIENT_STATIC_BORINGSSL ON")
----

=== Building from source

Full instructions to build the SDK from source are given in the README of our https://github.com/couchbase/couchbase-cxx-client[GitHub repository].
