= Best Practices
:description: Speed up your application development, with some best practices for using Couchbase SDKs.
:page-toclevels: 2
:page-aliases: concept-docs:errors.adoc,concept-docs:rbac.adoc



// Note to editors
// 
// This page pulls in content from -sdk-common-
// and code samples from -example-dir-
// 
// It can be seen built at wwww.


[abstract]
{description}


// see .NET doc on this


From batching and reactive APIs, to unit tests and handling errors.
There's plenty that can be done to remove bottlenecks in development and in performance, and this page can be your checklist of areas not to neglect as you develop your app.



== Security

But before worrying about bottlenecks, let's put security concerns first.

Security is a process, and not just a set of checkboxes -- but there are key areas you must check off as you move from development, through testing, to deploying in production.


=== Roles and RBAC

include::{version-common}@sdk:pages:partial$rbac.adoc[tag=security]


// *TODO* update and add Capella here


// ==== Users, Resources, Roles, and Privileges

include::{version-common}@sdk:pages:partial$rbac.adoc[tag=roles]


== Performance

Couchbase's Data Service uses a fast binary protocol, which will always outperform JSON streamed over HTTP from {sqlpp} queries.
If you know the key (ID) of a document, then use the xref:howtos:kv-operations.adoc[Data Service].

If you need pessimistic logging, in particular if you need to lock documents for multi-document ACID transactions, then anything you can do at the schema level to reduce the number of documents locked simultaneously wil remvoe a bottleneck to updating the affected documents.  



=== Dealing with Timeout Errors


// see also
// https://couchbasecloud.atlassian.net/wiki/spaces/CST/pages/1993769712/Java+-+Debugging+KV+Timeouts
// in Support wiki

* LAN-type connection of client and server is recommended in production, but WAN development is a reality pre-production.
Ensure that you're familiar with the 
xref:ref:client-settings.adoc#constrained-network-environments[best timeout options for WAN environments],
or at least set a xref:ref:client-settings.adoc#wan-development[WAN development Configuration Profile].


// write after more LZA added
////
=== Read From Replica

Advanced zone aware....
////


=== Concurrency and Async APIs

// ....this paragraph different for each SDK.

////
Choosing between the blocking, asynchronous, and reactive APIs for the Scala SDK is partly bound up with how (and where) you want to handle exceptions.

* Synchronous operations are blocking, and return a Scala `Try` object.
This contains either the result or a _Throwable_ exception,
which can be pattern matched over (using `flatMap` in more complex cases).
* The asynchronous API returns Scala `Future`, representing the execution of an asynchronous task and the promise of a future result.
An `ExecutionContext` must be provided, to give a thread pool for handling whatever is returned.
* The reactive API is a more natural fit for network-aware, fault tolerant programs, 
and will provide full back pressure for streaming results from large {sqlpp} or Search queries.
////

See the xref:howtos:concurrent-async-apis.adoc[Async & Reactive APIs page] for practical examples.



=== Bulk Get, Multi-Get, and Network Latency

include::{version-common}@sdk:shared:partial$best-practices.adoc[tag=bulk-get]


==== When to Use Bulk Get

include::{version-common}@sdk:shared:partial$best-practices.adoc[tag=bulk-get-async-platform]



== Error Handling

Best practices for error handling in {cpp} depend somewhat upon your choice of API:
future, or callback based, as covered in the xref:concurrent-async-apis.adoc[async and reactive API guide].
That guide also covers how errors are actually returned and handled.
Your application should always check if an operation returned an error, and potentially handle any specific error codes that may have returned.
See also the xref:howtos:error-handling.adoc[error handling guide],
which covers specific errors, along with a broader look at error handling strategies.

// == Testing
//
// Integrate developing with the {name-sdk} into your accustomed test framework.




////
== General Approach to Scala Exceptions

 When the unexpected happens, take a step-by-step approach.

include::{version-common}@sdk:shared:partial$errors.adoc[tag=exception]

// include::{version-common}@sdk:shared:partial$errors.adoc[tag=ref]

include::{version-common}@sdk:shared:partial$errors.adoc[tag=durability]

include::{version-common}@sdk:shared:partial$errors.adoc[tag=diag]
////




// Slow Operations Logging
include::{version-common}@sdk:shared:partial$errors.adoc[tag=observability]

// until opentelemetry release for link below, could add note on API to expose own tracing features?
// include::{version-common}@sdk:shared:partial$errors.adoc[tag=rto]





// Missing APIs
// For anything that is not covered by the SDK, 
// for example
// a raw FTS query from the SDK...
// use the HTTP client: 

////
public class CouchbaseHttpClient
extends Object
A specialized HTTP client for making requests to Couchbase Server.
Get an instance by calling Cluster.httpClient().

Example usage:

 public static String getAutoFailoverSettings(Cluster cluster) {
   HttpResponse response = cluster.httpClient().get(
       HttpTarget.manager(),
       HttpPath.of("/settings/autoFailover"));

   if (!response.success()) {
     throw new RuntimeException(
         "Failed to get auto-failover settings. HTTP status code " +
             response.statusCode() + "; " + response.contentAsString());
   }

   return response.contentAsString();
 }

 public static void disableAutoFailover(Cluster cluster) {
   HttpResponse response = cluster.httpClient().post(
       HttpTarget.manager(),
       HttpPath.of("/settings/autoFailover"),
       HttpPostOptions.httpPostOptions()
           .body(HttpBody.form(Map.of("enabled", "false"))));

   if (!response.success()) {
     throw new RuntimeException(
         "Failed to disable auto-failover. HTTP status code " +
             response.statusCode() + "; " + response.contentAsString());
   }
 }
 
////
// https://docs.couchbase.com/sdk-api/couchbase-java-client/com/couchbase/client/java/http/CouchbaseHttpClient.html




== Additional Information

SDKs are client to Couchbase Server -- whether Capella Database-As-A-Service, or self-managed -- and in some areas it would be wise to take a fully rounded approach.
Read up on security and performance considerations relevant to your use case.

=== Couchbase Security Best Practices

* xref:cloud:security:security.adoc[Security Best Practices in Capella]
* xref:server:learn:security/security-overview.adoc[Security for self-managed Couchbase Server]

=== Role-Based Access Control

// *TODO* add Capella info

include::{version-common}@sdk:pages:partial$rbac.adoc[tag=info]




// other SDK's docs
//
// add in Python
// https://docs.couchbase.com/sdk-api/couchbase-python-client/couchbase_api/parallelism.html
//
// 
